I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/akti.rpy", line 102, in script
    text "I tak Lia ruszyła przed siebie opuszczając obecne życie. Prawdopodobnie nikt już jej nigdy nie widział."
Exception: Sayer 'text' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/akti.rpy", line 102, in script
    text "I tak Lia ruszyła przed siebie opuszczając obecne życie. Prawdopodobnie nikt już jej nigdy nie widział."
  File "renpy/ast.py", line 671, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'text' is not defined.

