I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 483, in script
    g "Spokojnie spokojnie! Jeszcze musisz mi powiedzieć jedną rzecz..."
Exception: Sayer 'g' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 483, in script
    g "Spokojnie spokojnie! Jeszcze musisz mi powiedzieć jedną rzecz..."
  File "renpy/ast.py", line 671, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'g' is not defined.

